version: '3'


services:
  app:
    build: .
    image: vocabularybot
    container_name: vocabularybot
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - "/home/user/.env"