name: Deploy buy runner

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  setEnv:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: set up Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
  prepare-environment:
    runs-on: self-hosted
    needs: setEnv
    steps:
#      - name: test1
#        run: id
#      - name: test1
#        run: ls -a
#      - name: test12
#        run: cd /home
#      - name: test12
#        run: ls -a
#      - name: test2
#        run: cd /home/runner/work/
#      - name: test3
#        run: ls -a
      - name: Stop and remove containers, networks
        run: docker-compose down
      - name: Remove unused data
        run: docker system prune -a -f
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker-compose
        run: docker-compose up -d